### ISSUE TITLE
Control max discharge AMPS

### ISSUE THREAD

**Issue by finalbillybong** [incub77/solis2mqtt#10]
Can anyone help me with controling the max discharge amps on my Solis Hybrid 6K?

I know the register I need is 43118 but I'm not 100% sure what I need to put in my solis_modbus.yaml. 

```
- name: discharge_power_limitation
  description: Discharge Power limitation
  unit: "A"
  active: true
  modbus:
    register: 43118
    read_type: register
    function_code: 3
    write_function_code: 6
    number_of_decimals: 2
    signed: false
  homeassistant:
    device: number
    min: 0
    max: 70
    step: 0.5
    state_class:
    device_class:
```

If I read register 33144 it shows the discharge limit as 100 - If really want to be able to manually set it to zero. 

I am using modbus register codes found [here](https://www.scss.tcd.ie/Brian.Coghlan/Elios4you/RS485_MODBUS-Hybrid-BACoghlan-201811228-1854.pdf)

**Comment by NickSutton** [comment]
This block allows me to write to the solis discharge limit;

````
#Discharge Amps
- name: write_battery_discharge_limit
  active: true
  modbus:
    register: 43142
    number_of_decimals: 0
    write_function_code: 6
    input_type: holding
    signed: false
````

 I then send a MQTT message from HA to the write_battery_discharge_limit topic
